# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4a748291f63a7b7306c6f278fc9ecd6423c16757016e467ad6dab646aa6ba47a54bda1e475f9cdaf4e0f8711535e9281cfdfde2d0eb372c5104532a4972c9549

test:
  secret_key_base: c50b2f005324203d003dc531b8fb00ce2e053f44aaa042b5784df435b1ee66c4eff1c8355ad46194c1c361892b92564d264a805a21bb360cb2a76f4f3b6226aa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
